### ISSUE TITLE
Potential Copyright and License Violations

### ISSUE THREAD

**Issue by dsieger** [LiangliangNan/Easy3D#86]
Hi,

we are the developers of the [Polygon Mesh Processing Library](https://www.pmp-library.org) ([GitHub](https://github.com/pmp-library/pmp-library)) as well as its predecessor [Surface_mesh](https://opensource.cit-ec.de/projects/surface_mesh).

It looks like you copied a good chunk of our code, removed all our copyright and licensing information, and added your name, copyright, and license instead. This concerns the core SurfaceMesh data structure as well as several algorithms such as remeshing, fairing, hole filling, parameterization, subdivision, simplification, plus their respective helper classes. This list is not exhaustive.

This is a serious copyright violation. We ask you to fix this issue as quickly as possible. Please go through your code and bring back the correct copyright/licensing information. Otherwise, we have to take further legal action.

We suggest to publicly and prominently make clear where a good chunk of the code comes from. This is not a legal requirement, but a matter of good style. We are developing our library as open-source so that others can benefit from it. What we ask for in return is to respect our very permissive license terms and copyright. Give credit where credit is due.

We discussed this issue with other authors of open source projects in geometry processing. In case you copied not only from us, you might want to clean up and properly acknowledge this code as well.

Daniel Sieger
Mario Botsch

**Comment by LiangliangNan** [comment]
Oh, indeed. The copyright notices in all the files were replaced. 
I will fix this soon. Thank you for pointing out this and apologies for any issue caused by this.

**Comment by LiangliangNan** [comment]
Hi @dsieger, the copyright and licensing information in the source code have been corrected (they were batch replaced when I updated the copyright notice for the whole project in an earlier release). 
Besides, I've added an acknowledgment section in the ReadMe file stating that the implementation of the concerned surface mesh algorithms was taken from PMP. 
Thank you for contributing to the open-source community the great implementations of these algorithms!
Please kindly check and let me know if further changes are needed.

**Comment by dsieger** [comment]
Thanks for reacting promptly.

There is still an issue with your copyright lines in the algorithm files: It predates the actual publication date of the library. There's no way you can claim copyright 2015 for something that was not even published at that point. This should match the year whenever you imported our code and made actual changes.

**Comment by LiangliangNan** [comment]
Yes, that is definitely true 👍 
Just fixed all these lines: 2015 -> 2020.  
Please let me know if any comments.   Thanks!
